[package]
name = "testbox"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
description = "A fast test runner that works out of the box with zero dependencies."
readme = "README.md"
license = "MIT"
repository = "https://github.com/dhuan/testbox"
homepage = "https://github.com/dhuan/testbox"
keywords = ["test", "automation"]
categories = ["command-line-utilities", "development-tools::testing"]
exclude = ["/docs"]

[dependencies]
clap = { version = "4.6.5", features = ["derive", "unstable-doc"] }
mlua = { version = "0.12.0", features = ["lua54", "vendored", "serde", "serialize"] }
rand = "0.10.2"
regex = "1.13.1"
reqwest = { version = "0.13.4", features = ["blocking", "json"] }
serde = "1.0.229"
serde_json = "1.0.151"
url = "2.5.8"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
