name: Build & Test

on:
  push:
    branches: ["*"]
  pull_request:

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rustup_toolchain: stable
          - os: macos-latest
            target: aarch64-apple-darwin
            rustup_toolchain: stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rustup_toolchain }}

      - name: Cargo build
        run: cargo build

      - name: Set up mock
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -L https://github.com/dhuan/mock/releases/download/v1.4.16/mock_v1.4.16_linux-386.tar.gz | tar xz
          chmod u+x mock
          cd -
          PATH=${PATH}:~/bin sh -c 'make test'

      - name: E2E test
        run: PATH=${PATH}:~/bin sh -c 'make test'
